### PR TITLE
Content of topics

### PR DESCRIPTION
**Pull request by Mayank4git**
index of contents of python tutorials

### CODE REVIEW

**Comment by Mayank4git** [comment]
index of python topics

**Comment by itspratham** [comment]
Hi,
Kindly go through the topics which is listed in Python content folder

**Comment by Mayank4git** [comment]
I have done it already other repository named topics_Python

**Comment by itspratham** [comment]
Oh great

**Comment by Mayank4git** [comment]
You can check it there and then please mention me too .

**Review by itspratham — APPROVED** [review]

**Pull request closed without merging**
